Hungarian Translation of the SkyKings Bot
SkyKings-Guild/translations pull request #1
Opened 2022-08-13 08:14 UTC by Bilovisnake

Adds translations for `locale`

- [] I have followed the guidelines listed in the README.

2022-08-13 08:44 UTC, plun1331 requested changes
Have a few more checks to run once I get home after the 28th

2022-08-13 08:44 UTC, plun1331 commented on translations/hu-HU.json
> +        "Módosítani tudod a konfigurációkat a '/config edit' paranccsal!"
the command name here should be translated and placed in an inline codeblock (\`\`)

2022-08-13 08:44 UTC, plun1331 commented on translations/hu-HU.json
> +        "Módosítani tudod a konfigurációkat a '/config edit' paranccsal!"
Same as above

2022-08-13 08:44 UTC, plun1331 commented on translations/hu-HU.json
> +        "Ha többet szeretnél tudni, használd a '/premium info' parancsot."
Same as above

2022-08-13 08:44 UTC, plun1331 commented on translations/hu-HU.json
> +        "{option} {value}-re lett állítva!!"
Double exclamation mark

```suggestion
        "{option} {value}-re lett állítva!"
```

2022-08-13 08:44 UTC, plun1331 commented on translations/hu-HU.json
> +        "Add a szerverhez a  `/config guilds add-guild` paranccsal."
Same as first comment

2022-08-13 08:44 UTC, plun1331 commented on translations/hu-HU.json
> +        "Add a szerverhez a `/config guilds add-guild` paranccsal."
Same as above

2022-08-13 08:44 UTC, plun1331 commented on translations/hu-HU.json
> +        "Add a szerverhez a `/config guilds add-guild` paranccsal."
Same as above

2022-08-13 08:44 UTC, plun1331 commented on translations/hu-HU.json
> +        "Add a szerverhez a `/config guilds add-guild` paranccsal."
Same as above

2022-08-13 08:44 UTC, plun1331 commented on translations/hu-HU.json
> +        "Add a szerverhez a `/config guilds add-guild` paranccsal."
ame as above

2022-08-13 08:44 UTC, plun1331 commented on translations/hu-HU.json
> +        "Add a szerverhez a `/config guilds add-guild` paranccsal."
Same as above
I give up on marking all of these

2022-08-13 08:44 UTC, plun1331 commented on translations/hu-HU.json
> +      "disabled": [" **{event}** kikapcsolva."]
Spacing, unless this was also done in the English translation
```suggestion
      "enabled": ["**{event}** bekapcsolva."],
      "disabled": ["**{event}** kikapcsolva."]
```

2022-08-13 08:44 UTC, plun1331 commented on translations/hu-HU.json
> +    "description": "Kijelez egy  listát a guild tagjairól.",
Spacing
```suggestion
    "description": "Kijelez egy listát a guild tagjairól.",
```

2022-08-13 08:44 UTC, plun1331 commented on translations/hu-HU.json
> +        "**This event ends on {end_date} ({end_relative})**"
Translation where

2022-08-13 08:44 UTC, plun1331 commented on translations/hu-HU.json
> +      "jsonify": ["Dump to JSON File"]
Does this have a translation

2022-08-13 09:05 UTC, Bilovisnake commented
I think I fixed it, but I don't know if Github updated it.

2022-08-19 19:52 UTC, Altpapier commented
Pretty sure the name should just be hu instead of hu-HU

2022-09-04 21:30 UTC, plun1331 commented
Added extra checks, please fix the following issues:
```
Incorrect list length at hu/config view/responses/description.1
Missing keys in hu/config guilds view/responses: noGuilds
Missing keys in hu/config guilds add-guild/responses: maxGuilds, premiumRequired
Missing keys in hu/lookup user/responses: TRADER, TRADER_NAME
Extra keys in hu/lookup user/responses: IRL_TRADER_NAME, IRL_TRADER
Missing keys in hu/verify link/responses: cancelled
```

2022-09-07 22:27 UTC, plun1331 requested changes

2022-09-07 22:27 UTC, plun1331 commented on translations/hu.json
> +        "Hypixel Status Channel: {status_channel}\n",
I've just added these in, please translate

2022-09-07 22:27 UTC, plun1331 commented on translations/hu.json
> +      "onlineWithMode": ["**{name}** jelenleg {game}-t játszik.\nMód: {mode}."],
Slide this in here as well
https://github.com/SkyKings-Guild/translations/blob/52c3263324591342a900b9b8ace1f073fc2ee300/translations/en-US.json#L1531

2022-09-11 02:10 UTC, plun1331 requested changes

2022-09-11 02:10 UTC, plun1331 commented on translations/hu.json
> +        "Módosítani tudod a konfigurációkat a '/config módosítás' paranccsal!"
The whole command name should be translated, including top level
Should also be in backticks for `this effect`

2022-09-11 02:10 UTC, plun1331 commented on translations/hu.json
> +        "Módosítani tudod a konfigurációkat a '/config módosítás' paranccsal!"
The whole command name should be translated, including top level
Should also be in backticks for `this effect`

2022-09-11 02:10 UTC, plun1331 commented on translations/hu.json
> +        "Ha többet szeretnél tudni, használd a '/premium infomáció' parancsot."
The whole command name should be translated, including top level
Should also be in backticks for `this effect`

2022-09-11 02:10 UTC, plun1331 commented on translations/hu.json
> +        "Több információért futtasd a /premium infó parancsot."
The whole command name should be translated, including top level
Should also be in backticks for `this effect`

2022-09-11 02:10 UTC, plun1331 commented on translations/hu.json
> +          "Ha többet szeretnél tudni, használd a '/premium információ' parancsot."
The whole command name should be translated, including top level
Should also be in backticks for `this effect`

2022-09-11 02:10 UTC, plun1331 commented on translations/hu.json
> +        "Add a szerverhez a  `/config guilds guild-hozzáadás` paranccsal."
The whole command name should be translated, including top level
Should also be in backticks for `this effect`

2022-09-11 02:10 UTC, plun1331 commented on translations/hu.json
> +        "Add a szerverhez a `/config guilds guild-hozzáadás` paranccsal."
The whole command name should be translated, including top level
Should also be in backticks for `this effect`

2022-09-11 02:10 UTC, plun1331 commented on translations/hu.json
> +        "Add a szerverhez a `/config guilds guild-hozzáadása` paranccsal."
The whole command name should be translated, including top level
Should also be in backticks for `this effect`

2022-09-11 02:10 UTC, plun1331 commented on translations/hu.json
> +        "Add a szerverhez a `/config guilds guild-hozzáadása` paranccsal."
The whole command name should be translated, including top level
Should also be in backticks for `this effect`

2022-09-11 02:10 UTC, plun1331 commented on translations/hu.json
> +        "Add a szerverhez a `/config guilds guild-hozzáadása` paranccsal."
The whole command name should be translated, including top level
Should also be in backticks for `this effect`

2022-09-11 02:10 UTC, plun1331 commented on translations/hu.json
> +        "Add a szerverhez a `/config guilds guild-hozzáadása` paranccsal."
The whole command name should be translated, including top level
Should also be in backticks for `this effect`

2022-09-11 02:10 UTC, plun1331 commented on translations/hu.json
> +        "Add a szerverhez a `/config guilds add-guild` paranccsal."
The whole command name should be translated, including top level
Should also be in backticks for `this effect`

2022-09-11 02:10 UTC, plun1331 commented on translations/hu.json
> +        "Regisztráld a `/config guilds add-rank` paranccsal."
The whole command name should be translated, including top level
Should also be in backticks for `this effect`

2022-09-11 02:10 UTC, plun1331 commented on translations/hu.json
> +        "Add a szerverhez a `/config guilds add-guild` parancshoz."
The whole command name should be translated, including top level
Should also be in backticks for `this effect`

2022-09-11 02:10 UTC, plun1331 commented on translations/hu.json
> +        "Átlagos Websocket lappangási idő : {avg_ws_latency:,} ms\n",
```suggestion
        "Átlagos Websocket lappangási idő: {avg_ws_latency:,} ms\n",
```

2022-09-11 02:10 UTC, plun1331 commented on translations/hu.json
> +        "description": "Itt állíthatod be, hogy GvG (Guild versus Guild) legyen az esemény. Ehhez a lehetőséghez prémiummal kell rendelkezni."
Guild versus Guild should be translated if possible

2022-09-11 02:10 UTC, plun1331 commented on translations/hu.json
> +        "\n\n*Ha ez nem igaz, kérjük jelentsd ezt a játékost `/report` paranccsal.*"
The command name should be translated
Should also be in backticks for `this effect`

2022-09-11 02:10 UTC, plun1331 commented on translations/hu.json
> +        "\n\n*Ha ez nem igaz, kérjük jelentsd ezt a játékost `/report` paranccsal.*"
The command name should be translated
Should also be in backticks for `this effect`

2022-09-11 02:10 UTC, plun1331 commented on translations/hu.json
> +        "**Coins Per Bit**: {coinsPerBit:,.2f}"
Translate if possible

2022-09-11 02:10 UTC, plun1331 commented on translations/hu.json
> +        "Dungeon Item: {dungeon}\n"
Translate if possible

2022-09-11 02:10 UTC, plun1331 commented on translations/hu.json
> +        "> Bonus: {bonus_score:,}\n",
Translate if possible

2022-09-11 02:10 UTC, plun1331 commented on translations/hu.json
> +        "Preferred Games: {prefgames}"
Translate if possible

2022-09-11 02:10 UTC, plun1331 commented on translations/hu.json
> +        "XP History: \n{xp_history}"
Translate if possible

2022-09-11 02:10 UTC, plun1331 commented on translations/hu.json
> +        "**6)** Használd a `/verify link` parancsot, hogy hozzákösd a Minecraft fiókod a Discord fiókodhoz.\n",
The whole command name should be translated, including top level
Should also be in backticks for `this effect`

2022-09-11 02:10 UTC, plun1331 commented on translations/hu.json
> +          "Ha már véget ért, kitörölheted a `/event delete` paranccsal."
The whole command name should be translated, including top level
Should also be in backticks for `this effect`

2022-09-11 02:10 UTC, plun1331 commented on translations/hu.json
> +          "További információért írd be a `/premium info` parancsot."
The whole command name should be translated, including top level
Should also be in backticks for `this effect`

2022-09-11 02:10 UTC, plun1331 commented on translations/hu.json
> +          "Ellenőrizhetsz a `/verify` paranccsal."
The whole command name should be translated, including top level
Should also be in backticks for `this effect`

2022-09-11 02:10 UTC, plun1331 commented on translations/hu.json
> +          "Több információért használd a `/premium info` parancsot."
The whole command name should be translated, including top level
Should also be in backticks for `this effect`

2022-09-11 02:10 UTC, plun1331 commented on translations/hu.json
> +          "Több információért használd a `/premium info` parancsot."
The whole command name should be translated, including top level
Should also be in backticks for `this effect`

2022-09-11 02:10 UTC, plun1331 commented on translations/hu.json
> +          "Nem vagy az eseményben. Csatlakozz az `/event join` paranccsal."
The whole command name should be translated, including top level
Should also be in backticks for `this effect`

2022-09-20 22:14 UTC, plun1331 commented on translations/hu.json
> +      "description": "A scammerek ezen a Google Form-on jelenthetőek: [Google Form](https://forms.gle/ANud6cd9mTx2efbh9)."
hello yes i changed original text pls retranslate
https://github.com/SkyKings-Guild/translations/blob/aa6b9f96aa95e9fe07e792ddbe7f6c248048b3c3/translations/en-US.json#L1074

2023-06-05 17:51 UTC, plun1331 commented
Stale

2023-06-05 17:51 UTC, closed without merging